import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <div style={{ fontSize: '36px' }}>
       <p>
        Name - Kunal Dahat (Cloud/Devops Engineer)
        {/* <code>src/pages/index.js</code> */}
       </p>
      </div>

        

        <div className={styles.grid}>
          <a
            href="https://drive.google.com/file/d/12cBVH8A1t7oUOL37xOQbzlqFjPC2OcX-/view?usp=sharing"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Resume <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Click to see my awsome resume
            </p>
          </a>

          <a
            // href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Skills <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Kubernetes, Docker, Linux, Git, Ansible, Nginx ,AWS ,GCP, Azure, Grafana, DNS, CICD, SES, LB, S3, VPC, SSL
            </p>
          </a>

          <a
            href="https://www.linkedin.com/in/kunal-dahat"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              LinkedIn <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              
            </p>
          </a>

          <a
            // href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Deployments <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Have deployed 50+ UAT deployment on kubernetes via CICD & 10+ Projects Prod deployed
            </p>
          </a>
        </div>
      </main>
    </>
  )
}
